version: '3'

services:
  bitcoin-jvm: 
    image: quarkus/bitcoin-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-bitcoin:3306/bitcoin_negotiation?autoReconnect=true
    networks:
      - mysql-db    
    ports:
      - 8080:8080
    depends_on:
      - mysql-bitcoin

  mysql-bitcoin: 
    image: aluracursos/mysql-quarkus-db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql.bitcoin:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - mysql-db

networks:
 mysql-db:
  driver: bridge

volumes:
  mysql.bitcoin: